services:
  postgres:
    image: "postgres:15.4"
    container_name: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:$POSTGRES_PORT
    volumes:
      - postgress_data:/var/lib/postgresql/data
  
  postsservice:
    image: "postsservice"
    container_name: "postsservice"
    build:
      context: ./services/postsservice
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOSTNAME=$POSTGRES_HOSTNAME
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 8000:$POSTSSERVICE_PORT
    depends_on:
      - postgres
    command: ["uvicorn", "main:app", "--port", $POSTSSERVICE_PORT, "--host", "0.0.0.0"]

volumes:
  postgress_data:
    external: true
