services:
  postgres:
    image: "postgres:15.4"
    container_name: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - postgress_data:/var/lib/postgresql/data
  
  config:
    image: "config"
    container_name: "config"
    build:
      context: ./services/config
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: ["unicorn", "main:app", "--port", "8000"]
    # command: ["python3", "main.py"]

volumes:
  postgress_data:
    external: true
